bursaKasder/Models/EntityModels/LayoutViewModel.cs
namespace bursaKasder.Models.EntityModels
{
    public class LayoutViewModel
    {
        public BKD_OrganizationInformation OrganizationInfo { get; set; }
        public BKD_Contact ContactInfo { get; set; }
    }
}

bursaKasder/Controllers/LoginController.cs
using bursaKasder.HelperClasses;
using bursaKasder.Models.EntityModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;


namespace bursaKasder.Controllers
{
    public class LoginController : Controller
    {
        private readonly DbContextManager _context;

        public LoginController(DbContextManager context)
        {
            _context = context;
        }

        private static Dictionary<string, int> loginAttempts = new Dictionary<string, int>();
        private static Dictionary<string, DateTime> lockedUsers = new Dictionary<string, DateTime>();
        public IActionResult Index()
        {
            return View(new LoginViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }


            if (lockedUsers.ContainsKey(model.adm_Username) && lockedUsers[model.adm_Username] > DateTime.Now)
            {
                TimeSpan remainingTime = lockedUsers[model.adm_Username] - DateTime.Now;
                ModelState.AddModelError("", $"Çok fazla hatalı giriş yaptınız. Lütfen {remainingTime.Minutes} dakika {remainingTime.Seconds} saniye sonra tekrar deneyin.");
                return View(model);
            }

            var Users = _context.BKD_Admins.FirstOrDefault(a => a.adm_Username == model.adm_Username);

            if (Users == null || Users.adm_Password != model.adm_Password)
            {
                IncrementLoginAttempts(model.adm_Username);
                ModelState.AddModelError("", "Hatalı kullanıcı adı veya şifre. Lütfen tekrar deneyiniz.");
                return View(model);
            }

            // Kullanıcı doğrulandı, giriş başarılı
            ResetLoginAttempts(model.adm_Username);

            //HttpContext.Session.SetString("Admin_Id", Users.adm_ID);
            HttpContext.Session.SetString("Admin_name", Users.adm_Name);
            HttpContext.Session.SetString("Admin_surname", Users.adm_Surname);

            return RedirectToAction("Index", "Admin");

        }

        private void IncrementLoginAttempts(string userId)
        {
            if (!loginAttempts.ContainsKey(userId))
                loginAttempts[userId] = 0;

            loginAttempts[userId]++;

            if (loginAttempts[userId] >= 3)
            {
                lockedUsers[userId] = DateTime.Now.AddMinutes(1); // 1 dakika boyunca giriş yapamaz
                Task.Delay(TimeSpan.FromMinutes(1)).ContinueWith(t => ResetLoginAttempts(userId));
            }
        }

        private void ResetLoginAttempts(string userId)
        {
            if (loginAttempts.ContainsKey(userId))
                loginAttempts.Remove(userId);

            if (lockedUsers.ContainsKey(userId))
                lockedUsers.Remove(userId);
        }
        public ActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }


    }
}

bursaKasder/Controllers/PagesController.cs
using bursaKasder.HelperClasses;
using bursaKasder.Models;
using bursaKasder.Models.EntityModels;
using bursaKasder.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;

namespace bursaKasder.Controllers
{
    public class PagesController : Controller
    {

        private readonly Get_AdminService _getAdminService;
        private readonly Post_AdminService _postAdminService;
        private readonly DbContextManager _context;

        public PagesController(Post_AdminService postAdminService, Get_AdminService getAdminService, DbContextManager context)
        {
            _context = context;
            _postAdminService = postAdminService;
            _getAdminService = getAdminService;


        }
        public IActionResult Index()
        {
            var MainData = _context.BKD_OrganizationInformation.FirstOrDefault();

            if (MainData == null)
            {
                return NotFound("Veri bulunamadı.");
            }
            return View();
        }
        public IActionResult KasderStructure()
        {
            var structureData = _context.BKD_OrganizationalStructure.Where(s => s.OS_Status == 0).ToList();

            if (structureData == null)
            {
                return NotFound("Teşkilat Yapısı Hakkında Bilgi bulunamadı.");
            }
            return View(structureData);
        }

        public IActionResult contact_us()
        {
            var contactData = _context.BKD_Contact.FirstOrDefault();

            if (contactData == null)
            {
                return NotFound("Hakkımızda bilgisi bulunamadı.");
            }
            return View(contactData);
        }

        public IActionResult about_us()
        {
            var aboutData = _context.BKD_About.FirstOrDefault();


            if (aboutData == null)
            {
                return NotFound("Hakkımızda bilgisi bulunamadı.");
            }


            return View(aboutData);
        }


        public IActionResult news_FromUs()
        {
            var newsData = _context.BKD_NewsFromUs.Where(s => s.newsU_Status == 0).OrderByDescending(n => n.newsU_ID).ToList();

            var OIData = _context.BKD_OrganizationInformation.FirstOrDefault();
            ViewBag.Logo = OIData.OI_Logo;

            if (newsData == null)
            {
                return NotFound("Veri bulunamadı");
            }
            return View(newsData);
        }

        [HttpGet]
        public IActionResult showNewsDetail(int? id)
        {
            var postDetail = _context.BKD_NewsFromUs.FirstOrDefault(n => n.newsU_ID == id);
            if (postDetail == null)
            {
                return NotFound();
            }
            return View(postDetail);
        }

        public IActionResult news_FromKast()
        {
            return View();
        }
        public IActionResult events()
        {
            var eventData = _context.BKD_Events.Where(s => s.ev_Status == 0).OrderByDescending(n => n.ev_ID).ToList();

            if (eventData == null) { return NotFound(); }

            return View(eventData);
        }

        [HttpGet]
        public IActionResult showEventDetail(int id)
        {
            var eventDetail = _context.BKD_Events.Where(s => s.ev_Status == 0 ).Include(e => e.EventPhotos).FirstOrDefault(e => e.ev_ID == id);

            if (eventDetail == null)
            {
                return NotFound();
            }

            var viewModel = new EventViewModel
            {
                ev_ID = eventDetail.ev_ID,
                ev_Title = eventDetail.ev_Title,
                ev_Content = eventDetail.ev_Content,
                ev_Date = eventDetail.ev_Date,
                ev_MainPhoto = eventDetail.ev_MainPhoto,
                EventPhotos = eventDetail.EventPhotos.Select(p => p.evP_Photo).ToList()
            };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult ContactUsAdd()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ContactUsAdd(BKD_ContactUs cUS)
        {
            if (ModelState.IsValid)
            {
                cUS.conU_DateMessage = DateTime.Now;
                cUS.conU_Status = 0;

                _context.BKD_ContactUs.Add(cUS);
                _context.SaveChanges();

                TempData["SuccessMessage"] = "Mesajınız başarıyla gönderildi.";
                return RedirectToAction("Index", "Home");
            }

            TempData["ErrorMessage"] = "Mesaj gönderme başarısız! Lütfen tüm alanları doldurduğunuzdan emin olun.";
            return View(cUS);
        }
    }
}

bursaKasder/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<!-- [Head] start -->
<head>

    <!-- [Meta] -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description">
    <meta name="keywords">
    <meta name="author" content="CodedThemes">
    <link rel="icon" href="~/UploadsOIPhoto/e6d40bf8-95d6-4c8a-98aa-5f2ef060a181.png">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
    <!-- jQuery'yi sayfanıza ekleyin -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <!-- SweetAlert2 Kütüphanesi -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>


    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;400;500;600;700&display=swap" id="main-font-link">

    @* <link rel="stylesheet" href="~/css/adminAssets/fonts/tabler-icons.min.css"> *@

    <link rel="stylesheet" href="~/css/adminAssets/fonts/feather.css">

    <link rel="stylesheet" href="~/css/adminAssets/fonts/fontawesome.css">

    <link rel="stylesheet" href="~/css/adminAssets/fonts/material.css">

    <link rel="stylesheet" href="~/css/adminAssets/style.css" id="main-style-link">
    <link rel="stylesheet" href="~/css/adminAssets/style-preset.css">

</head>

<body data-pc-preset="preset-1" data-pc-direction="ltr" data-pc-theme="light">

    <script src="~/js/adminAssets/popper.min.js"></script>
    <script src="~/js/adminAssets/simplebar.min.js"></script>
    <script src="~/js/adminAssets/bootstrap.min.js"></script>
    <script src="~/js/adminAssets/custom-font.js"></script>
    <script src="~/js/pcoded.js"></script>
    <script src="~/js/adminAssets/feather.min.js"></script>

    <!-- [ Pre-loader ] start -->
    <div class="loader-bg">
        <div class="loader-track">
            <div class="loader-fill"></div>
        </div>
    </div>
    <!-- [ Pre-loader ] End -->
    <!-- [ Sidebar Menu ] start -->
    <nav class="pc-sidebar">
        <div class="navbar-wrapper">
            <div class="m-header">
                    <!-- ========   Change your logo from here   ============ -->
                <img src="~/UploadsOIPhoto/e6d40bf8-95d6-4c8a-98aa-5f2ef060a181.png" class="img-fluid logo-lg" alt="logo">
            </div>
            <div class="navbar-content">
                <ul class="pc-navbar">
                    <li class="pc-item">
                        <a asp-controller="Admin" asp-action="Index" class="pc-link">

                            <span class="pc-mtext">Anasayfa</span>
                        </a>
                    </li>
                    <li class="pc-item">
                        <a href="/Admin/UserList" class="pc-link">

                            <span class="pc-mtext">Admin Paneli Kullanıcıları</span>
                        </a>
                    </li>
                    <li class="pc-item">
                        <a href="/Admin/conUList" class="pc-link">

                            <span class="pc-mtext">Bizimle İletişime Geçenler</span>
                        </a>
                    </li>

                    <li class="pc-item pc-caption">
                        <label>-- Site Yönetimi</label>
                        <i class="ti ti-dashboard"></i>
                    </li>

                    <li class="pc-item">
                        <a asp-controller="Admin" asp-action="NewsList" class="pc-link">

                            <span class="pc-mtext">Haberler</span>
                        </a>
                    </li>
                    <li class="pc-item">
                        <a asp-controller="Admin" asp-action="eventList" class="pc-link">

                            <span class="pc-mtext">Etkinlikler</span>
                        </a>
                    </li>
                    <li class="pc-item">
                        <a asp-controller="Admin" asp-action="AnnouncementsList" class="pc-link">
    
                            <span class="pc-mtext">Duyurular</span>
                        </a>
                    </li>



                    <li class="pc-item pc-caption">
                        <label>-- Genel Bilgiler</label>
                        <i class="ti ti-dashboard"></i>
                    </li>
                    <li class="pc-item">
                        <a asp-controller="Admin" asp-action="bkdInfo" class="pc-link">

                            <span class="pc-mtext">Ana Bilgiler</span>
                        </a>
                    </li>
                    <li class="pc-item">
                        <a asp-controller="Admin" asp-action="aboutInfo" class="pc-link">

                            <span class="pc-mtext">Hakkında Bilgileri</span>
                        </a>
                    </li>
                    <li class="pc-item">
                        <a asp-controller="Admin" asp-action="contactInfo" class="pc-link">

                            <span class="pc-mtext">İletişim Bilgileri</span>
                        </a>
                    </li>
                    <li class="pc-item">
                        <a asp-controller="Admin" asp-action="OSStructureList" class="pc-link">

                            <span class="pc-mtext">Teşkilat Yapısı</span>
                        </a>
                    </li>


                   @*  <li class="pc-item pc-hasmenu">
                        <a href="#!" class="pc-link">
                            <span class="pc-micon"><i class="ti ti-menu"></i></span><span class="pc-mtext">
                                Diğer İşlemler
                            </span><span class="pc-arrow"><i data-feather="chevron-right"></i></span>
                        </a>
                        <ul class="pc-submenu">

                            <!-- Admin Paneli Oluşturma Aşaması için oluşturdum-->
                            <li class="pc-item"><a class="pc-link" asp-controller="Admin" asp-action="addAbout">Hakkımızda Ekle</a></li>
                            <li class="pc-item"><a class="pc-link" asp-controller="Admin" asp-action="addContact">İletişim Bilgileri Ekle</a></li>
                            <li class="pc-item"><a class="pc-link" asp-controller="Admin" asp-action="addOI">Dernek Bilgileri Ekle</a></li>
                            <li class="pc-item"><a class="pc-link" asp-controller="Admin" asp-action="addNewsFromUs">Haber Ekle</a></li>
                            <li class="pc-item"><a class="pc-link" asp-controller="Admin" asp-action="addOS">Dernek Sorumlusu Ekle</a></li>
                            <li class="pc-item"><a class="pc-link" asp-controller="Admin" asp-action="addEvent">Etkinlik Ekle</a></li>



                            <li class="pc-item"><a class="pc-link" asp-controller="Admin" asp-action="NewsList">Haberler Liste</a></li>
                            <li class="pc-item"><a class="pc-link" asp-controller="Admin" asp-action="eventList">Etkinlik Liste</a></li>
                            <li class="pc-item"><a class="pc-link" asp-controller="Admin" asp-action="OSStructureList">OS Liste</a></li>
                            <li class="pc-item"><a class="pc-link" asp-controller="Admin" asp-action="contactInfo">İletişim Bilgileri Ayarları</a></li>
                            <li class="pc-item"><a class="pc-link" asp-controller="Admin" asp-action="aboutInfo">Hakkında Bilgileri Ayarları</a></li>
                            <li class="pc-item"><a class="pc-link" asp-controller="Admin" asp-action="bkdInfo">Ana Bilgiler</a></li>

                        </ul>
                    </li> *@
                </ul>

            </div>
        </div>
    </nav>
    <!-- [ Sidebar Menu ] end --> <!-- [ Header Topbar ] start -->
    <header class="pc-header">
        <div class="header-wrapper">
            <!-- [Mobile Media Block] start -->
            <div class="me-auto pc-mob-drp">
                <ul class="list-unstyled">
                    <!-- ======= Menu collapse Icon ===== -->
                    <li class="pc-h-item pc-sidebar-collapse">
                        <a href="#" class="pc-head-link ms-0" id="sidebar-hide">
                            <i class="ti ti-menu-2"></i>
                        </a>
                    </li>
                    <li class="pc-h-item pc-sidebar-popup">
                        <a href="#" class="pc-head-link ms-0" id="mobile-collapse">
                            <i class="ti ti-menu-2"></i>
                        </a>
                    </li>

                </ul>
            </div>
            <!-- [Mobile Media Block end] -->
        <ul>
            <li class="dropdown pc-h-item header-user-profile">
                    
                    <div class="tab-content" id="mysrpTabContent">
                        <div class="tab-pane fade show active" id="drp-tab-1" role="tabpanel" aria-labelledby="drp-t1" tabindex="0">
                            <a asp-controller="Login" asp-action="Logout" class="dropdown-item">         
                                <span>Çıkış</span>
                            </a>
                        </div>
                    </div>
            </li>
        </ul>
        </div>
        
    </header>

    <main >
        @RenderBody() 
    </main>


    <footer class="pc-footer">
        <div class="footer-wrapper container-fluid">
            <div class="row">
                <div class="col-sm my-1 text-center">
                    <p class="m-0">
                        &copy; 2025 <strong>BURSA KASTAMONULULAR DAYANIŞMA DERNEĞİ</strong> |
                        <a href="https://www.elsayazilim.com/" target="_blank">Elsa Yazılım </a>
                        | Tüm Hakları Saklıdır.
                    </p>
                </div>

            </div>
        </div>
   </footer>
    

    <script>layout_change('light');</script>

    <script>change_box_container('false');</script>

    <script>layout_rtl_change('false');</script>

    <script>preset_change("preset-1");</script>

    <script>font_change("Public-Sans");</script>

</body>
<!-- [Body] end -->
</html>

bursaKasder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>

    <!-- jQuery (Önce Yüklenmeli) -->
    <script src="~/js/vendors/jquery-3.6.1.min.js"></script>

    <!-- Bootstrap CSS (CDN) -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">

    <!-- Favicon -->
    <link rel="icon" href="~/UploadsOIPhoto/e6d40bf8-95d6-4c8a-98aa-5f2ef060a181.png">

    <!-- 3. Parti Kütüphaneler -->
    <link rel="stylesheet" href="~/css/vendors/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/css/vendors/animate.css">
    <link rel="stylesheet" href="~/css/vendors/swiper.min.css">
    <link rel="stylesheet" href="~/css/vendors/splitting.css">

    <!-- FontAwesome (CDN) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;600;700;800;900&display=swap">

    <!-- Ana CSS Dosyası -->
    <link rel="stylesheet" href="~/css/styles-ltr.css">



</head>
<body class=" overlay-is-linear-gradient ">
    <header class="page-header menu-on-end " id="page-header">
        <!--start navbar-->
        <div class="container">
            <nav class="main-navbar " id="main-nav">

                 <a class="navbar-brand " href="#">
                    <img class="brand-logo light-logo img-fluid " src="~/UploadsOIPhoto/e6d40bf8-95d6-4c8a-98aa-5f2ef060a181.png " alt="" />
                    <img class="brand-logo dark-logo img-fluid " src="~/UploadsOIPhoto/7e1090f0-6644-4049-a808-94bc8b77271a.jpg" alt="" />
                </a> 

                <div class="menu-toggler-btn"><span></span><span></span><span></span></div>
                <div class=" navbar-menu-wraper  " id="navbar-menu-wraper">
                    <ul class="navbar-nav  mobile-menu ">
                        <li class="nav-item"><a class="nav-link  " asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                        <li class="nav-item"><a class="nav-link  " asp-controller="Pages" asp-action="about_us">Hakkımızda</a></li>
                        <li class="nav-item"><a class="nav-link  " asp-controller="Pages" asp-action="KasderStructure">Derneğimiz</a></li>
                        <li class="nav-item"><a class="nav-link  " asp-controller="Pages" asp-action="events">Etkinliklerimiz</a></li>
                        <li class="nav-item"><a class="nav-link  " asp-controller="Pages" asp-action="news_FromUs">Haberler</a></li>


@*                         <li class="nav-item has-sub-menu">
                            <a class="nav-link  " href="#0">Haberler<i class="fas fa-chevron-down down-Arrow-icon"> </i></a>
                            <ul class="sub-menu ">
                                <li class="nav-item sub-menu-item"><a class="nav-link sub-menu-link  " asp-controller="Pages" asp-action="news_FromUs">Bizden Haberler</a></li>
                                <li class="nav-item sub-menu-item"><a class="nav-link sub-menu-link  " asp-controller="Pages" asp-action="news_FromKast">Kastamonudan Haberler</a></li>
                            </ul>
                        </li> *@
                        @* <li class="nav-item"><a class="nav-link  " asp-controller="" asp-action="">Duyurular</a></li> *@
                        <li class="nav-item"><a class="nav-link  " asp-controller="Pages" asp-action="contact_us">İletişim</a></li>
                        <li class="nav-item"><a class="nav-link  " asp-controller="Pages" asp-action="ContactUsAdd">Bize Ulaşın</a></li>
                    </ul>
            </nav>
        </div>
        <!--End navbar-->
    </header>

    <main role="main">
        @RenderBody() <!-- Sayfaların içeriği buraya gelecek -->
    </main>

    <footer class="page-footer dark-color-footer" id="page-footer">
        <div class="container">
            <div class="row footer-cols">
                <div class="col-12 col-md-8 col-lg-4  footer-col wow fadeInUp " data-wow-delay="0.3s">
                    <h6 class=" footer-col-title  ">BURSA KASTAMONULULAR DAYANIŞMA DERNEĞİ</h6>
                    <div class="footer-col-content-wrapper">
                        <p class="footer-text-about-us ">
                           
                        </p>
                        <div class="social-icons">
                            <div class="sc-wraper dir-row sc-size-32">
                                <ul class="sc-list">
                                    <li class="sc-item" title="Facebook">
                                        <a class="sc-link" href="https://www.facebook.com/kasderbursa
"><i class="fab fa-facebook-f sc-icon"></i></a></li>
                                    <li class="sc-item" title="youtube"><a class="sc-link" href="#0"><i class="fab fa-youtube sc-icon"></i></a></li>
                                    <li class="sc-item" title="instagram"><a class="sc-link" href="https://www.instagram.com/bursakastamonululardernegi/" target="_blank"><i class="fab fa-instagram sc-icon"></i></a></li>
                                    <li class="sc-item" title="X"><a class="sc-link" href="https://x.com/bkasder"><i class="fab fa-x-twitter sc-icon"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-2  footer-col wow fadeInUp " data-wow-delay="0.5s">
                </div>
                <div class="col-12 col-md-8   col-lg-4 footer-col wow fadeInUp " data-wow-delay=".9s">
                    <h6 class=" footer-col-title    ">İletişim Bilgileri</h6>
                    <div class="footer-col-content-wrapper">
                        <div class="contact-info-card"><i class="fas fa-envelope icon"></i><a class="text-lowercase  info" href="info.bursa.kasder@gmail.com">info.bursa.kasder@gmail.com</a></div>

                        <div class="contact-info-card"><i class="fas fa-map-marker-alt icon"></i><span class="text-uppercase  info">Bursa, Türkiye.</span></div>
                        <div class="contact-info-card"><i class="fas fa-mobile-alt icon"></i><a class="info" href="tel:+90 -">+90 -     </a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyrights ">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-6">
                        <p class="creadits">
                            &copy; 2025
                            Created by:
                            <a class="link" href="https://www.elsayazilim.com/">ELSA YAZILIM</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/vendors/jquery-3.6.1.min.js"></script>

    <!--     bootstrap     -->
    <script src="~/js/vendors/bootstrap.bundle.min.js"></script>

    <!--     fancybox     -->
    <script src="~/js/vendors/jquery.fancybox.min.js"></script>

    <!--     countTo     -->
    <script src="~/js/vendors/jquery.countTo.js"></script>

    <!--     wow     -->
    <script src="~/js/vendors/wow.min.js"></script>

    <!--     swiper     -->
    <script src="~/js/vendors/swiper.min.js"></script>

    <!--     isotope     -->
    <script src="~/js/vendors/isotope-min.js"></script>

    <!--     Splitting     -->
    <script src="~/js/vendors/splitting.min.js"></script>

    <!--     main     -->
    <script src="~/js/main.js"></script>
</body>
</html>